### ISSUE TITLE
repo not working ?

### ISSUE THREAD

**Issue by lokilust** [Bizarrus/Sentora-LetsEncrypt#9]
zppy repo add sentcrypt.tk

zppy update

zppy install letsencrypt

Module to be installed letsencrypt
No package match, check you have added the correct repo!

Please help

**Comment by Bizarrus** [comment]
The development has stopped, because sentora is too much old and will not be longer active supported.

**Comment by lokilust** [comment]
I wonder if i update my OS from Ubuntu 12.04 to 16.04 ?
